// GENERATED by scripts/contracts.mjs from docs/features/multi-currency-summary/contracts/openapi.yaml — do not edit.
export interface paths {
    "/expenses/{expenseId}/rate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id витрати — legacy `expenses.id TEXT` з `randomUUID()` (v4). */
                expenseId: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Замінити курс на збереженій витраті
         * @description Сума й валюта введення не змінюються — міняється лише rate snapshot (Invariants).
         *     Попереднє значення ніде не зберігається (AC-05). Статус поїздки НЕ перевіряється:
         *     finished блокує нові витрати, не атрибути наявних (AC-08) — тому 409 тут немає.
         *     Шлях без `tripId`: `SetExpenseRate(expenseId, rate)` поїздки не приймає.
         */
        put: operations["setExpenseRate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Створити поїздку (опційно — одразу з base currency)
         * @description As-built ендпойнт; фіча додає лише необов'язкову `baseCurrency` (sad.md §5,
         *     `CreateTrip`). Без неї поїздка створюється як раніше, `baseCurrency: null`.
         */
        post: operations["createTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/base-currency": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — legacy `trips.id TEXT` з `randomUUID()` (v4). */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Задати або змінити base currency поїздки
         * @description Перше задання дозволене завжди. Зміну вже заданої валюти блокує хоча б одна
         *     витрата з ЯВНИМ rate snapshot (`RatedExpensesPort`); похідний курс 1 лок не
         *     тримає (AC-07, ADR-0003/0004). Після зміни витрати у старій валюті стають
         *     «без курсу» і видні в лічильнику. Статус поїздки не перевіряється.
         */
        put: operations["setTripBaseCurrency"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — legacy `trips.id TEXT` з `randomUUID()` (v4). */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Додати витрату — з курсом, без курсу або у base currency
         * @description `rate` необов'язковий. Для витрати у base currency поле не потрібне — курс 1
         *     похідний на читанні і не зберігається (AC-06, ADR-0003), тож у відповіді
         *     `expense.rate: null`, а витрата вже counted у `budget`. Курс при поїздці без
         *     base currency — 422 `expenses.base_currency_not_set`. Витрата приймається
         *     навіть з перевищенням budget — overspend лише сигнал у `budget` (Invariants).
         */
        post: operations["addExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — legacy `trips.id TEXT` з `randomUUID()` (v4). */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        /**
         * Підсумок — сирі суми, converted total, лічильник без курсу, залишок
         * @description `lines` — сирі суми по (категорія, валюта), як і раніше. `converted` — Σ
         *     `Rate.apply(amount)` (half-up, minor units) по витратах з ефективним курсом;
         *     `null`, поки у поїздки немає base currency. `budget` — та сама BudgetBlock:
         *     remaining рахується з тієї ж Σ, тож `converted.withoutRate === budget.uncounted`
         *     (ADR-0003). Дрібні курси не округлюються в нуль (AC-03b, шкала 10⁹).
         */
        get: operations["getTripSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddExpenseRequest: {
            /** @description Minor units (as-built поле; `expenses.amount_minor INTEGER`). */
            amount: number;
            category: components["schemas"]["ExpenseCategory"];
            currency: components["schemas"]["CurrencyCode"];
            rate?: components["schemas"]["Rate"];
            /** Format: date */
            spentAt: string;
        };
        AddExpenseResponse: {
            budget: components["schemas"]["BudgetBlock"] | null;
            expense: components["schemas"]["Expense"];
        };
        /** @description `shared/Balance` (trip-budget ADR-0004) — знакове ціле в minor units + валюта. */
        Balance: {
            amount: number;
            currency: components["schemas"]["CurrencyCode"];
        };
        /**
         * @description trip-budget ADR-0002/0003 — одна форма у двох відповідях. Семантика counted
         *     змінена ADR-0003 цієї фічі: counted = має ефективний курс (явний або 1 для
         *     base currency), Σ — у перерахованих сумах.
         */
        BudgetBlock: {
            budget: components["schemas"]["Money"];
            counted: number;
            overspend: boolean;
            remaining: components["schemas"]["Balance"];
            /** @description Витрати без ефективного курсу; дорівнює `converted.withoutRate`. */
            uncounted: number;
        };
        /** @description sad.md §5 `converted: { total, withoutRate }` (ADR-0003). */
        ConvertedTotal: {
            total: components["schemas"]["Money"];
            /** @description Кількість витрат поза перерахунком (AC-04). */
            withoutRate: number;
        };
        CreateTripRequest: {
            baseCurrency?: components["schemas"]["CurrencyCode"];
            country: string;
            /**
             * Format: date
             * @description Не раніше `startsAt` (as-built zod refine + `trips` CHECK).
             */
            endsAt: string;
            /** Format: date */
            startsAt: string;
            title: string;
        };
        /**
         * @description ISO 4217, верхній регістр; патерн замість довідника (trip-budget sad.md §8).
         * @example EUR
         */
        CurrencyCode: string;
        ErrorDetails: {
            issues?: components["schemas"]["ValidationIssue"][];
        };
        ErrorResponse: {
            /** @description `<bc>.<snake(Sentinel)>`, bc ∈ trips | expenses | shared | http. */
            code: string;
            details?: components["schemas"]["ErrorDetails"];
            message: string;
        };
        Expense: {
            amount: components["schemas"]["Money"];
            category: components["schemas"]["ExpenseCategory"];
            /** Format: uuid */
            id: string;
            /** @description Явний rate snapshot або `null`. Для витрати у base currency — `null`; курс 1 похідний і видно його лише через counted (ADR-0003). */
            rate: components["schemas"]["Rate"] | null;
            /**
             * Format: date-time
             * @description As-built — ISO date-time з `Date`.
             */
            spentAt: string;
            /** Format: uuid */
            tripId: string;
        };
        /** @enum {string} */
        ExpenseCategory: "transport" | "lodging" | "food" | "tickets" | "other";
        /** @description `shared/Money` — ціле невід'ємне в minor units + валюта. Буває сумою (підсумки), тож межа — JS safe integer. */
        Money: {
            amount: number;
            currency: components["schemas"]["CurrencyCode"];
        };
        /**
         * @description `shared/Rate` (ADR-0002) — курс до base currency: додатний десятковий рядок,
         *     ≤ 9 знаків до і після коми (`rate_nano BIGINT` = значення × 10⁹, CHECK > 0).
         *     Рядок, не JSON number: float дає `1e-7`, і `Rate.parse` зламався б на валідному вводі.
         * @example 0.039800000
         */
        Rate: string;
        SetBaseCurrencyRequest: {
            baseCurrency: components["schemas"]["CurrencyCode"];
        };
        SetExpenseRateRequest: {
            rate: components["schemas"]["Rate"];
        };
        /** @description As-built `TripSummaryLine` — сирі суми без перерахунку. */
        SummaryLine: {
            category: components["schemas"]["ExpenseCategory"];
            currency: components["schemas"]["CurrencyCode"];
            total: components["schemas"]["Money"];
        };
        /**
         * @description As-built поля `Trip` + `baseCurrency`. Потребує presenter-а: серіалізація класу
         *     віддала б і `budget` з trip-budget (flag F4).
         */
        Trip: {
            baseCurrency: components["schemas"]["CurrencyCode"] | null;
            country: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: uuid */
            id: string;
            /**
             * Format: date-time
             * @description As-built — `Date` серіалізується як ISO date-time, хоча в БД `DATE` (flag F5).
             */
            startsAt: string;
            status: components["schemas"]["TripStatus"];
            title: string;
        };
        /** @enum {string} */
        TripStatus: "planned" | "active" | "finished";
        TripSummary: {
            budget: components["schemas"]["BudgetBlock"] | null;
            converted: components["schemas"]["ConvertedTotal"] | null;
            /** @description Агрегат (≤ 5 категорій × валюти поїздки), не колекція сутностей — без пагінації. */
            lines: components["schemas"]["SummaryLine"][];
        };
        ValidationIssue: {
            message: string;
            /** @description Шлях до поля через крапку (з zod `issue.path`). */
            path: string;
        };
    };
    responses: {
        /** @description `BaseCurrencyLockedError` — є витрати з явним rate snapshot (AC-07). */
        BaseCurrencyLocked: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "trips.base_currency_locked",
                 *       "message": "Base currency is locked while expenses have explicit rates"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description `ExpenseNotFoundError` — витрати немає (flow 3). */
        ExpenseNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "expenses.expense_not_found",
                 *       "message": "Expense not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description `TripNotFoundError` (BC expenses) — поїздки немає (as-built). */
        ExpenseTripNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "expenses.trip_not_found",
                 *       "message": "Trip not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description 422 з двома кодами: форма (`http.validation_failed` — у т.ч. нульовий або
         *     від'ємний курс, AC-02) або курс для поїздки без base currency
         *     (`expenses.base_currency_not_set` — `BaseCurrencyNotSetError`).
         */
        RateRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description `TripDoesNotExistError` (BC trips, trip-budget sad.md §5) — поїздки немає. */
        TripDoesNotExist: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "trips.trip_does_not_exist",
                 *       "message": "Trip not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description `TripNotAcceptingExpensesError` — поїздка finished (CONTEXT Invariants). */
        TripNotAcceptingExpenses: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "expenses.trip_not_accepting_expenses",
                 *       "message": "Trip is not accepting expenses"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Ключа немає або він не збігається (перевірка до сховища). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "http.unauthorized",
                 *       "message": "Unauthorized"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Тіло не пройшло zod-валідацію. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "http.validation_failed",
                 *       "message": "Request body is invalid",
                 *       "details": {
                 *         "issues": [
                 *           {
                 *             "path": "baseCurrency",
                 *             "message": "Invalid string"
                 *           }
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Id витрати — legacy `expenses.id TEXT` з `randomUUID()` (v4). */
        ExpenseId: string;
        /** @description Id поїздки — legacy `trips.id TEXT` з `randomUUID()` (v4). */
        TripId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setExpenseRate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id витрати — legacy `expenses.id TEXT` з `randomUUID()` (v4). */
                expenseId: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "rate": "0.039750000"
                 *     }
                 */
                "application/json": components["schemas"]["SetExpenseRateRequest"];
            };
        };
        responses: {
            /** @description Курс замінено; converted total і залишок перераховуються на читанні. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "00000000-0000-4000-8000-0000000000e1",
                     *       "tripId": "00000000-0000-4000-8000-000000000001",
                     *       "amount": {
                     *         "amount": 150000,
                     *         "currency": "CZK"
                     *       },
                     *       "category": "food",
                     *       "spentAt": "2026-10-03T00:00:00.000Z",
                     *       "rate": "0.039750000"
                     *     }
                     */
                    "application/json": components["schemas"]["Expense"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["ExpenseNotFound"];
            422: components["responses"]["RateRejected"];
        };
    };
    createTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "title": "Test Trip",
                 *       "country": "PT",
                 *       "startsAt": "2026-10-01",
                 *       "endsAt": "2026-10-15",
                 *       "baseCurrency": "EUR"
                 *     }
                 */
                "application/json": components["schemas"]["CreateTripRequest"];
            };
        };
        responses: {
            /** @description Поїздку створено. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "00000000-0000-4000-8000-000000000001",
                     *       "title": "Test Trip",
                     *       "country": "PT",
                     *       "startsAt": "2026-10-01T00:00:00.000Z",
                     *       "endsAt": "2026-10-15T00:00:00.000Z",
                     *       "status": "planned",
                     *       "baseCurrency": "EUR"
                     *     }
                     */
                    "application/json": components["schemas"]["Trip"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    setTripBaseCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — legacy `trips.id TEXT` з `randomUUID()` (v4). */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "baseCurrency": "EUR"
                 *     }
                 */
                "application/json": components["schemas"]["SetBaseCurrencyRequest"];
            };
        };
        responses: {
            /** @description Base currency збережено. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "00000000-0000-4000-8000-000000000001",
                     *       "title": "Test Trip",
                     *       "country": "PT",
                     *       "startsAt": "2026-10-01T00:00:00.000Z",
                     *       "endsAt": "2026-10-15T00:00:00.000Z",
                     *       "status": "active",
                     *       "baseCurrency": "EUR"
                     *     }
                     */
                    "application/json": components["schemas"]["Trip"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["TripDoesNotExist"];
            409: components["responses"]["BaseCurrencyLocked"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    addExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — legacy `trips.id TEXT` з `randomUUID()` (v4). */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddExpenseRequest"];
            };
        };
        responses: {
            /** @description Витрату прийнято. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddExpenseResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["ExpenseTripNotFound"];
            409: components["responses"]["TripNotAcceptingExpenses"];
            422: components["responses"]["RateRejected"];
        };
    };
    getTripSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — legacy `trips.id TEXT` з `randomUUID()` (v4). */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
