// GENERATED by scripts/contracts.mjs from docs/features/trip-budget/contracts/openapi.yaml — do not edit.
export interface paths {
    "/trips/{tripId}/budget": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — legacy `trips.id TEXT` з `randomUUID()` (v4). */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Задати або замінити budget поїздки
         * @description Перше задання фіксує base currency поїздки; заміна можлива лише в тій
         *     самій валюті (AC-02). Значення перезаписується без журналу (AC-07).
         *     Дозволено в будь-якому статусі поїздки, включно з `finished` (AC-09).
         *     PUT ідемпотентний за семантикою — `Idempotency-Key` не потрібен.
         *     Ендпойнт NEW — живого дроту немає, форма визначена цим контрактом.
         */
        put: operations["setTripBudget"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — legacy `trips.id TEXT` з `randomUUID()` (v4). */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Додати витрату й отримати overspend signal
         * @description Витрата приймається завжди, навіть якщо перевищує budget — budget
         *     ніколи не блокує (CONTEXT Invariants, AC-04). Overspend — не помилка,
         *     а `budget.overspend: true` у тілі відповіді 201 (ADR-0003).
         *     `budget: null`, якщо budget поїздки не задано. Спільний ендпойнт з
         *     multi-currency-summary — там же `rate` (ще не в scope цієї фічі).
         */
        post: operations["addExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — legacy `trips.id TEXT` з `randomUUID()` (v4). */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        /**
         * Підсумок поїздки з блоком залишку
         * @description `lines` — агрегат по (категорія, валюта), як і раніше (as-built форма
         *     збережена 1:1). `budget` — той самий блок, що у відповіді додавання
         *     витрати, або `null`, якщо budget не задано. Від'ємний `remaining`
         *     показується від'ємним (AC-03b); якщо всі витрати чужовалютні —
         *     `remaining` дорівнює повному budget, а `uncounted` — кількості всіх
         *     витрат (AC-06b). Спільний ендпойнт з multi-currency-summary — там же
         *     `converted` (ще не в scope цієї фічі).
         */
        get: operations["getTripSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddExpenseRequest: {
            /** @description Minor units (as-built поле; `expenses.amount_minor INTEGER`). */
            amount: number;
            category: components["schemas"]["ExpenseCategory"];
            currency: components["schemas"]["CurrencyCode"];
            /** Format: date */
            spentAt: string;
        };
        AddExpenseResponse: {
            budget: components["schemas"]["BudgetBlock"] | null;
            expense: components["schemas"]["Expense"];
        };
        /** @description `shared/Balance` (ADR-0004) — знакове ціле в minor units + валюта. */
        Balance: {
            amount: number;
            currency: components["schemas"]["CurrencyCode"];
        };
        /** @description Результат чистої функції BudgetBlock (ADR-0002) — одна форма у двох відповідях (ADR-0003). Форма ідентична `BudgetBlock` у контракті multi-currency-summary (яка розширює семантику `counted`, тут — базова, ADR-0002). */
        BudgetBlock: {
            budget: components["schemas"]["Money"];
            /** @description Кількість витрат у base currency, що увійшли в порівняння. */
            counted: number;
            /** @description `true`, якщо `remaining.amount < 0`. Сигнал, не заборона. */
            overspend: boolean;
            /** @description budget − Σ counted; може бути від'ємним (Balance, ADR-0004; AC-03b). */
            remaining: components["schemas"]["Balance"];
            /** @description Кількість витрат в інших валютах — у порівняння не увійшли (AC-06, AC-06b). */
            uncounted: number;
        };
        /**
         * @description Код ISO 4217 у верхньому регістрі (sad.md §8; повного довідника у v1 немає — патерн).
         * @example EUR
         */
        CurrencyCode: string;
        ErrorDetails: {
            issues?: components["schemas"]["ValidationIssue"][];
        };
        ErrorResponse: {
            /**
             * @description `<bc>.<snake(Sentinel)>`, bc ∈ trips | expenses | shared | http.
             * @example expenses.trip_not_found
             */
            code: string;
            details?: components["schemas"]["ErrorDetails"];
            message: string;
        };
        Expense: {
            amount: components["schemas"]["Money"];
            category: components["schemas"]["ExpenseCategory"];
            /** Format: uuid */
            id: string;
            /**
             * Format: date-time
             * @description As-built — `Date` серіалізується як ISO date-time, хоча в БД `DATE` (той самий факт документує multi-currency-summary F5 — спільний код, не нова розбіжність).
             */
            spentAt: string;
            /** Format: uuid */
            tripId: string;
        };
        /** @enum {string} */
        ExpenseCategory: "transport" | "lodging" | "food" | "tickets" | "other";
        /** @description `shared/Money` — ціле невід'ємне в minor units + валюта. Буває сумою (підсумки), тож межа — JS safe integer. */
        Money: {
            amount: number;
            currency: components["schemas"]["CurrencyCode"];
        };
        SetBudgetRequest: {
            /** @description Додатна сума budget у мінорних одиницях (AC-02 — нуль і від'ємні відхиляються; zod `int().positive()`, sad.md §8). Флет-поле, як `AddExpenseRequest.amount` — не `Money` (той дозволяє 0). */
            amount: number;
            baseCurrency: components["schemas"]["CurrencyCode"];
        };
        /** @description As-built `TripSummaryLine` — сирі суми без перерахунку, форма 1:1 з живим дротом. */
        SummaryLine: {
            category: components["schemas"]["ExpenseCategory"];
            currency: components["schemas"]["CurrencyCode"];
            total: components["schemas"]["Money"];
        };
        /** @description Поїздка після задання/заміни budget (ADR-0001). Валюта живе всередині `budget.currency` — окремого поля `baseCurrency` тут немає (той самий принцип, що й у `BudgetBlock`). */
        TripBudget: {
            budget: components["schemas"]["Money"];
            /**
             * Format: date-time
             * @description Коли budget востаннє задано або замінено (`trips.budget_set_at`). Не журнал — одне значення (PRD §3).
             */
            budgetSetAt: string;
            /** Format: uuid */
            tripId: string;
        };
        TripSummary: {
            budget: components["schemas"]["BudgetBlock"] | null;
            /** @description Агрегат по (категорія, валюта) — не колекція сутностей, без пагінації (`.claude/rules/openapi.md` «Колекції»). */
            lines: components["schemas"]["SummaryLine"][];
        };
        ValidationIssue: {
            message: string;
            /** @description Шлях до поля в тілі запиту, через крапку (`amount`, `baseCurrency`). */
            path: string;
        };
    };
    responses: {
        /**
         * @description Два коди з одним статусом 422: невалідна форма (`http.validation_failed`)
         *     або валюта не збігається з уже зафіксованою base currency поїздки
         *     (`trips.budget_currency_mismatch`, `BudgetCurrencyMismatchError` — planned,
         *     sad.md §5) — AC-02.
         */
        BudgetRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description `TripNotFoundError` (BC expenses, `src/expenses/domain/errors.ts`) — поїздки немає (as-built). Той самий код, що в multi-currency-summary. */
        ExpenseTripNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "expenses.trip_not_found",
                 *       "message": "Trip not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description `TripDoesNotExistError` (BC trips, sad.md §5 — planned, ще не в коді) — поїздки немає. Той самий код, що в multi-currency-summary (яка теж посилається на цей sentinel). */
        TripDoesNotExist: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "trips.trip_does_not_exist",
                 *       "message": "Trip not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description `TripNotAcceptingExpensesError` (BC expenses) — поїздка finished, витрати не приймаються (CONTEXT Invariants). Той самий код, що в multi-currency-summary. */
        TripNotAcceptingExpenses: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "expenses.trip_not_accepting_expenses",
                 *       "message": "Trip is not accepting expenses"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description Ключа немає або він не збігається. Відповідь однакова для наявної і
         *     неіснуючої поїздки — сховище не зачеплено (AC-08, sad.md §6 cross-cutting).
         *     Той самий код і форма, що в multi-currency-summary.
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "http.unauthorized",
                 *       "message": "Unauthorized"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Тіло запиту не пройшло zod-валідацію. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "http.validation_failed",
                 *       "message": "Request body is invalid",
                 *       "details": {
                 *         "issues": [
                 *           {
                 *             "path": "currency",
                 *             "message": "must match ^[A-Z]{3}$"
                 *           }
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Id поїздки — legacy `trips.id TEXT` з `randomUUID()` (v4). */
        TripId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setTripBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — legacy `trips.id TEXT` з `randomUUID()` (v4). */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "amount": 5000000,
                 *       "baseCurrency": "EUR"
                 *     }
                 */
                "application/json": components["schemas"]["SetBudgetRequest"];
            };
        };
        responses: {
            /** @description Budget збережено; підсумок відтепер показує блок залишку (AC-01). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "tripId": "00000000-0000-4000-8000-000000000001",
                     *       "budget": {
                     *         "amount": 5000000,
                     *         "currency": "EUR"
                     *       },
                     *       "budgetSetAt": "2026-10-01T08:30:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["TripBudget"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["TripDoesNotExist"];
            422: components["responses"]["BudgetRejected"];
        };
    };
    addExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — legacy `trips.id TEXT` з `randomUUID()` (v4). */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "amount": 4500,
                 *       "currency": "EUR",
                 *       "category": "food",
                 *       "spentAt": "2026-10-03"
                 *     }
                 */
                "application/json": components["schemas"]["AddExpenseRequest"];
            };
        };
        responses: {
            /** @description Витрату прийнято; блок budget обчислено тією ж BudgetBlock, що й у підсумку. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddExpenseResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["ExpenseTripNotFound"];
            409: components["responses"]["TripNotAcceptingExpenses"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getTripSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — legacy `trips.id TEXT` з `randomUUID()` (v4). */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "lines": [
                     *         {
                     *           "category": "food",
                     *           "currency": "EUR",
                     *           "total": {
                     *             "amount": 102500,
                     *             "currency": "EUR"
                     *           }
                     *         },
                     *         {
                     *           "category": "transport",
                     *           "currency": "UAH",
                     *           "total": {
                     *             "amount": 340000,
                     *             "currency": "UAH"
                     *           }
                     *         }
                     *       ],
                     *       "budget": {
                     *         "budget": {
                     *           "amount": 100000,
                     *           "currency": "EUR"
                     *         },
                     *         "remaining": {
                     *           "amount": -2500,
                     *           "currency": "EUR"
                     *         },
                     *         "counted": 7,
                     *         "uncounted": 2,
                     *         "overspend": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["TripSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
