// GENERATED by scripts/contracts.mjs from docs/features/trip-budget/contracts/openapi.yaml — do not edit.
export interface paths {
    "/trips/{trip_id}/budget": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — UUID v4 з застосунку (legacy `trips.id TEXT`). */
                trip_id: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Задати або замінити budget поїздки
         * @description Перше задання фіксує base currency поїздки; заміна можлива лише в тій
         *     самій валюті (AC-02). Значення перезаписується без журналу (AC-07).
         *     Дозволено в будь-якому статусі поїздки, включно з `finished` (AC-09).
         *     PUT ідемпотентний за семантикою — `Idempotency-Key` не потрібен.
         */
        put: operations["setTripBudget"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — UUID v4 з застосунку (legacy `trips.id TEXT`). */
                trip_id: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Додати витрату й отримати overspend signal
         * @description Витрата приймається завжди, навіть якщо перевищує budget — budget
         *     ніколи не блокує (CONTEXT Invariants, AC-04). Overspend — не помилка,
         *     а `budget.overspend: true` у тілі відповіді 201 (ADR-0003).
         *     `budget: null`, якщо budget поїздки не задано.
         */
        post: operations["addExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — UUID v4 з застосунку (legacy `trips.id TEXT`). */
                trip_id: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        /**
         * Підсумок поїздки з блоком залишку
         * @description `lines` — агрегат по (категорія, валюта), як і раніше. `budget` — той
         *     самий блок, що у відповіді додавання витрати, або `null`, якщо budget
         *     не задано. Від'ємний `remaining_minor` показується від'ємним (AC-03b);
         *     якщо всі витрати чужовалютні — `remaining_minor` дорівнює повному
         *     budget, а `uncounted` — кількості всіх витрат (AC-06b).
         */
        get: operations["getTripSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddExpenseRequest: {
            amount_minor: components["schemas"]["MinorAmount"];
            category: components["schemas"]["ExpenseCategory"];
            currency_code: components["schemas"]["CurrencyCode"];
            /** Format: date */
            spent_at: string;
        };
        AddExpenseResponse: {
            budget: components["schemas"]["BudgetBlock"] | null;
            expense: components["schemas"]["Expense"];
        };
        /** @description Результат чистої функції BudgetBlock (ADR-0002) — одна форма у двох відповідях (ADR-0003). */
        BudgetBlock: {
            base_currency: components["schemas"]["CurrencyCode"];
            budget_minor: number;
            /** @description Кількість витрат у base currency, що увійшли в порівняння. */
            counted: number;
            /** @description `true`, якщо remaining_minor < 0. Сигнал, не заборона. */
            overspend: boolean;
            /** @description budget − Σ counted у мінорних одиницях; може бути від'ємним (Balance, ADR-0004; AC-03b). */
            remaining_minor: number;
            /** @description Кількість витрат в інших валютах — у порівняння не увійшли (AC-06, AC-06b). */
            uncounted: number;
        };
        /**
         * @description Код ISO 4217 у верхньому регістрі (sad.md §8; повного довідника у v1 немає — патерн).
         * @example EUR
         */
        CurrencyCode: string;
        ErrorDetails: {
            issues?: components["schemas"]["ValidationIssue"][];
        };
        ErrorResponse: {
            /**
             * @description `<module>.<error_name>`, snake_case.
             * @example trip.not_found
             */
            code: string;
            details?: components["schemas"]["ErrorDetails"];
            message: string;
        };
        Expense: {
            amount_minor: components["schemas"]["MinorAmount"];
            category: components["schemas"]["ExpenseCategory"];
            currency_code: components["schemas"]["CurrencyCode"];
            /** Format: uuid */
            id: string;
            /** Format: date */
            spent_at: string;
            /** Format: uuid */
            trip_id: string;
        };
        /** @enum {string} */
        ExpenseCategory: "transport" | "lodging" | "food" | "tickets" | "other";
        /** @description Невід'ємна сума в мінорних одиницях (`Money`, INTEGER у БД). */
        MinorAmount: number;
        SetBudgetRequest: {
            base_currency: components["schemas"]["CurrencyCode"];
            /** @description Додатна сума budget у мінорних одиницях (AC-02 — нуль і від'ємні відхиляються). */
            budget_minor: number;
        };
        SummaryLine: {
            category: components["schemas"]["ExpenseCategory"];
            currency_code: components["schemas"]["CurrencyCode"];
            /** @description Σ amount_minor витрат цієї категорії в цій валюті. */
            total_minor: number;
        };
        TripBudget: {
            base_currency: components["schemas"]["CurrencyCode"];
            budget_minor: number;
            /** Format: uuid */
            trip_id: string;
        };
        TripSummary: {
            budget: components["schemas"]["BudgetBlock"] | null;
            lines: components["schemas"]["SummaryLine"][];
        };
        ValidationIssue: {
            message: string;
            /** @description Шлях до поля в тілі запиту, через крапку (`budget_minor`). */
            path: string;
        };
    };
    responses: {
        /**
         * @description Два коди з одним статусом 422: невалідна форма (`validation.invalid_payload`)
         *     або валюта не збігається з уже зафіксованою base currency поїздки
         *     (`budget.currency_mismatch`) — AC-02.
         */
        BudgetRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Поїздка у статусі finished — витрати не приймаються (CONTEXT Invariants). */
        TripNotAcceptingExpenses: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "trip.not_accepting_expenses",
                 *       "message": "Trip is finished and does not accept expenses"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Поїздки з таким id немає. */
        TripNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "trip.not_found",
                 *       "message": "Trip not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description Ключа немає або він не збігається. Відповідь однакова для наявної і
         *     неіснуючої поїздки — сховище не зачеплено (AC-08, sad.md §6 cross-cutting).
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "auth.unauthorized",
                 *       "message": "Unauthorized"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Тіло запиту не пройшло валідацію форми. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "validation.invalid_payload",
                 *       "message": "Request body is invalid",
                 *       "details": {
                 *         "issues": [
                 *           {
                 *             "path": "currency_code",
                 *             "message": "must match ^[A-Z]{3}$"
                 *           }
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Id поїздки — UUID v4 з застосунку (legacy `trips.id TEXT`). */
        TripId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setTripBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — UUID v4 з застосунку (legacy `trips.id TEXT`). */
                trip_id: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "budget_minor": 5000000,
                 *       "base_currency": "EUR"
                 *     }
                 */
                "application/json": components["schemas"]["SetBudgetRequest"];
            };
        };
        responses: {
            /** @description Budget збережено; підсумок відтепер показує блок залишку (AC-01). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "trip_id": "00000000-0000-4000-8000-000000000001",
                     *       "budget_minor": 5000000,
                     *       "base_currency": "EUR"
                     *     }
                     */
                    "application/json": components["schemas"]["TripBudget"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["TripNotFound"];
            422: components["responses"]["BudgetRejected"];
        };
    };
    addExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — UUID v4 з застосунку (legacy `trips.id TEXT`). */
                trip_id: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "amount_minor": 4500,
                 *       "currency_code": "EUR",
                 *       "category": "food",
                 *       "spent_at": "2026-10-03"
                 *     }
                 */
                "application/json": components["schemas"]["AddExpenseRequest"];
            };
        };
        responses: {
            /** @description Витрату прийнято; блок budget обчислено тією ж BudgetBlock, що й у підсумку. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddExpenseResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["TripNotFound"];
            409: components["responses"]["TripNotAcceptingExpenses"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getTripSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id поїздки — UUID v4 з застосунку (legacy `trips.id TEXT`). */
                trip_id: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "lines": [
                     *         {
                     *           "category": "food",
                     *           "currency_code": "EUR",
                     *           "total_minor": 102500
                     *         },
                     *         {
                     *           "category": "transport",
                     *           "currency_code": "UAH",
                     *           "total_minor": 340000
                     *         }
                     *       ],
                     *       "budget": {
                     *         "budget_minor": 100000,
                     *         "base_currency": "EUR",
                     *         "remaining_minor": -2500,
                     *         "counted": 7,
                     *         "uncounted": 2,
                     *         "overspend": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["TripSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
