#!/usr/bin/env node
// Contract toolchain: `node scripts/contracts.mjs gen|lint [slug...]`.
// gen  — openapi-typescript: docs/features/<slug>/contracts/openapi.yaml → src/contracts/<slug>.gen.ts
// lint — spectral (spectral:oas, .spectral.yaml) over the same files.
// Both tools live in tools/codegen (own node_modules): openapi-typescript needs the
// TypeScript 5 JS compiler API, the root project runs native TypeScript 7 without it.
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tools = join(root, 'tools', 'codegen', 'node_modules');
if (!existsSync(tools)) {
  console.error('tools/codegen/node_modules missing — run: npm --prefix tools/codegen ci');
  process.exit(2);
}

const [cmd, ...slugArgs] = process.argv.slice(2);
const featuresDir = join(root, 'docs', 'features');
const slugs = slugArgs.length
  ? slugArgs
  : readdirSync(featuresDir).filter((s) => existsSync(join(featuresDir, s, 'contracts', 'openapi.yaml')));
const specOf = (slug) => join(featuresDir, slug, 'contracts', 'openapi.yaml');

if (cmd === 'gen') {
  const { default: openapiTS, astToString } = await import(
    pathToFileURL(join(tools, 'openapi-typescript', 'dist', 'index.mjs')).href
  );
  mkdirSync(join(root, 'src', 'contracts'), { recursive: true });
  for (const slug of slugs) {
    const ast = await openapiTS(pathToFileURL(specOf(slug)), { alphabetize: true });
    const header = `// GENERATED by scripts/contracts.mjs from docs/features/${slug}/contracts/openapi.yaml — do not edit.\n`;
    const out = join(root, 'src', 'contracts', `${slug}.gen.ts`);
    writeFileSync(out, header + astToString(ast));
    console.log(`gen  ${slug} → src/contracts/${slug}.gen.ts`);
  }
} else if (cmd === 'lint') {
  const bin = join(tools, '@stoplight', 'spectral-cli', 'dist', 'index.js');
  execFileSync(process.execPath, [bin, 'lint', '--fail-severity', 'warn', ...slugs.map(specOf)], {
    stdio: 'inherit',
    cwd: root,
  });
} else {
  console.error('usage: node scripts/contracts.mjs gen|lint [slug...]');
  process.exit(2);
}
